// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKvnJfUEmL_gjdT4pcukGj7uAz5eDqzbI',
    appId: '1:846482770790:web:cbacfc1f03639a8af616a7',
    messagingSenderId: '846482770790',
    projectId: 'expenses-8ed77',
    authDomain: 'expenses-8ed77.firebaseapp.com',
    storageBucket: 'expenses-8ed77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpvlU5lBA2jtBSdJaIJF9lwt1WcgM593U',
    appId: '1:846482770790:android:e8ecc22f10382122f616a7',
    messagingSenderId: '846482770790',
    projectId: 'expenses-8ed77',
    storageBucket: 'expenses-8ed77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6l07LGNd2LHGdc_p6st93riacrDrS0CI',
    appId: '1:846482770790:ios:892980936f200bd6f616a7',
    messagingSenderId: '846482770790',
    projectId: 'expenses-8ed77',
    storageBucket: 'expenses-8ed77.appspot.com',
    iosBundleId: 'com.tsoka.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6l07LGNd2LHGdc_p6st93riacrDrS0CI',
    appId: '1:846482770790:ios:c8a0ac0c089e8eb9f616a7',
    messagingSenderId: '846482770790',
    projectId: 'expenses-8ed77',
    storageBucket: 'expenses-8ed77.appspot.com',
    iosBundleId: 'com.tsoka.expenses.RunnerTests',
  );
}
